### ISSUE TITLE
segmentation fault (core dumped) when attempting to generate an assembly graph (.gfa)

### ISSUE THREAD

**Issue by Paupiera** [GaetanBenoitDev/metaMDBG#2] opened 2023-06-26 17:55 UTC
Dear all,

Thanks for creating metaMDBG :). I am trying to generate an assembly graph (.gfa) after running metaMDBG. Unfortunately, a  
`segmentation fault (core dumped)` is raised. Here is the command that I am trying to run:

`./metaMDBG  gfa SRR15275211/ 110 --contigpath --readpath`
And here the error:
`Generating assembly graph for k value: 110 (corresponding sequence length = 21813 bps)
Generating unitig sequences...
Loading unitig sequences...
Creating assembly graph file...
Segmentation fault (core dumped)
`
I have writing permissions, and I am running this command with 250G of memory.  Do you have any idea of what could be causing the error?

Thanks in advance for your help,
Best,
Pau

**Comment by GaetanBenoitDev** [comment] 2023-06-27 07:50
Hello,

Thanks for using metaMDBG!
Unfortunately I can't reproduce the bug on this dataset.
Can you tell me if you have gfa files in SRR15275211/ (it should be ./SRR15275211/assemblyGraph_k110_21813bps.gfa).
If not can you show the contents of the following folder ./SRR15275211/tmp/pass_k110/ (with ls -lh ./SRR15275211/tmp/pass_k110/). This is where the temporary files for building the graph are located.

Thanks,
Gaëtan

**Comment by Paupiera** [comment] 2023-06-27 09:16
Dear Gaëtan,

Thanks for your fast reply. The content of SRR15275211 looks like that:
![SRR15275211](https://github.com/GaetanBenoitDev/metaMDBG/assets/38884866/38466f5b-4270-484b-be4b-e169e4b0d291)
And the content of SRR15275211/tmp/pass110 looks like that:
![pass_k110](https://github.com/GaetanBenoitDev/metaMDBG/assets/38884866/7dd50efb-07b4-4448-a255-48ef4a1dbda4)

SRR15275211/assemblyGraph_k110_21813bps.gfa does not exist. 

Thanks for your help,
Pau

**Comment by GaetanBenoitDev** [comment] 2023-06-27 09:25
Dear Pau,

Ok so this file unitgs.fasta.gz shouldn't be empty.
Can you now show me the output of:
tail -n 50 ./SRR15275211/tmp/logs.txt

**Comment by Paupiera** [comment] 2023-06-27 09:32
Dear Gaëtan,

There it goes:
![image](https://github.com/GaetanBenoitDev/metaMDBG/assets/38884866/642d029b-e5c7-436e-819b-86eff3aafb54)

**Comment by GaetanBenoitDev** [comment] 2023-06-27 09:50
Ok I will need the full log file, can you drop it here please.

**Comment by Paupiera** [comment] 2023-06-27 11:50
Here it goes:
[logs.txt](https://github.com/GaetanBenoitDev/metaMDBG/files/11881624/logs.txt)

**Comment by Paupiera** [comment] 2023-06-28 09:23
It works! Thank you so much for your help :). 

However, there are some things I do not understand about the assembly graph files generated from running the command `home/projects/cpr_10006/apps/metaMDBG gfa SRR15275211 k --contigpath --readpath` with different k values, 110 and 51:

1. I can see that `assemblyGraph_k110_21813bps_contigpath.tsv` and `assemblyGraph_k50_9813bps_contigpath.tsv` contain the same contigs in the first column, but the remaining columns can vary depending on the k value. More importantly, there are contigs that have no unitgs assigned to them.  I understand that depending on the k value, different unitigs can be defined, but how is it possible that with k=110 no unitigs define a contig? Does that mean that with this value of k those contigs can not be assembled?
2. I am interested in obtaining an assembly graph with the final set of contigs as nodes and the edges between those contigs. However I have the impression that each k value would define a different set of contigs, am I wrong?  In any case, would it be possible to generate those assembly graph files?

Thank you in advance for your help,
Best,
Pau

**Comment by GaetanBenoitDev** [comment] 2023-06-28 10:07
Great!

1) For the contigs without unitigs, I think it's because the provided graph is cleaned to reduce fragmentation, I will check if it is possible to provide the uncleaned graph instead so all contigs are assigned to the graph.
2) I won't be able to provide that unfortunatelly

**Comment by Paupiera** [comment] 2023-06-28 12:54
Makes sense. 

Thank you so much for developing such a great method!

**Closed** 2023-07-12 07:26 UTC
